image: golang:latest

before_script:
  - export GOPATH=$(pwd)

stages:
  - test

install_env_job:
  stage: test
  script:
  - echo $GOPATH
  - export PATH=$PATH:$GOPATH/bin
  - export PROJECT_DIR=$GOPATH/src/syifan/yaotsu
  - mkdir -p $PROJECT_DIR
  - cp -r ${CI_PROJECT_DIR}/ $PROJECT_DIR


build_job:
  stage: test
  script: 
  - cd $PROJECT_DIR && go get ./...
  - cd $PROJECT_DIR && go build ./...

test_job:
  stage: test
  script:
  - cd $PROJECT_DIR && ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
    
